kind = "web"
previewPath = "/"
title = "NetMoneyTools"
version = "1.0.0"
id = "artifacts/netmoneytools"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25118

[services.development]
run = "pnpm --filter @workspace/netmoneytools run dev"

[services.production.build]
args = ["pnpm", "--filter", "@workspace/netmoneytools", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/netmoneytools/dist/server/index.mjs"]

[services.production.run.env]
PORT = "25118"
NODE_ENV = "production"

[services.env]
PORT = "25118"
BASE_PATH = "/"
